name: docker

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-20.04-ppc64le
    steps:
      - name: Print Linux user
        run: whoami

      - name: Print user group info
        run: id

      - name: Print list of groups
        run: groups

      - name: Check Docker socket access
        run: sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock alpine docker ps

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: adysh97/http-server:latest
