name: Log Generator Workflow

on:
  workflow_dispatch:

jobs:
  generate-logs:
    name: Generate Logs - ${{ matrix.os }} [${{ matrix.runner_owner }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            runner_owner: "github-hosted"
          # - os: ubuntu-22.04-x64
          # runner_owner: "actions-runner-x64"
          - os: ubuntu-22.04-ppc64le
            runner_owner: "actions-runner-ppc64le"

    steps:
      - name: Generate Logs
        run: |
          echo "Generating large logs on ${{ matrix.os }}..."
          echo "Using Runner Owner: ${{ matrix.runner_owner }}..."
          time yes "example line log" | head -n 50000
          echo "Log generation complete for ${{ matrix.os }}."
