name: Log Generator Workflow

on:
  workflow_dispatch:

jobs:
  generate-logs:
    name: Generate Logs on ${{ matrix.os }} (Runner Owner: ${{ matrix.runner_owner }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            runner_owner: github
          - os: ubuntu-22.04-x64
            runner_owner: actions-runner-x64
          - os: ubuntu-22.04-ppc64le
            runner_owner: actions-runner-ppc64le

    steps:
      - name: Print Large Logs
        run: |
          echo "Generating large logs on ${{ matrix.os }} with runner owner ${{ matrix.runner_owner }}..."
          time yes "example line log" | head -n 1000000
          echo "Log generation complete for ${{ matrix.os }}."

