name: ruby-example

on:
  workflow_dispatch:
  push:

jobs:
  ruby:
    runs-on: ubuntu-latest-ppc64le
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: ruby hello.rb
