name: Stress and Disk Write

on:
  push:
    branches:
      - main

jobs:
  stress_and_disk_write:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Stress and Disk Write
        run: |
          # Writing 60 GB of random data to disk
          dd if=/dev/urandom of=randomdata bs=1M count=60000

          # Stressing RAM to 5 GB
          stress --vm 1 --vm-bytes 5G --vm-hang 0

          # Stressing CPU core 4
          stress --cpu 4
        shell: bash
