name: list vm details

on: [workflow_dispatch]

jobs:
  test_job:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-ppc64le]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Set up timestamp
        id: timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_ENV

      - name: Generate SHA
        id: sha
        run: echo "sha=$(echo -n ${{ env.timestamp }} | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: List VM Details
        run: |
          nproc   
          df -H 
          free -h

      - name: Get System Information
        run: |
          lscpu > cpu-info.txt
          free -h > memory-info.txt
          df -h > disk-info.txt
        shell: bash

      - name: Upload System Information
        uses: actions/upload-artifact@v4
        with:
          name: system-info-${{ env.sha }}
          path: |
            cpu-info.txt
            memory-info.txt
            disk-info.txt

      - name: Run commands
        run: |
          uname -a
          arch
          echo "sleeping for 5 minutes..."
          sleep 5m
          echo "wake up..."

      - name: List Installed Packages
        run: |
          dpkg-query -W -f='${Package}\n' > installed-packages.txt
        shell: bash

      - name: Upload Installed Packages
        uses: actions/upload-artifact@v4
        with:
          name: installed-packages-${{ env.sha }}
          path: installed-packages.txt
